### PR TITLE
Added IaaS specific provider details for virtual host manager

### PR DESCRIPTION
**Pull request by pranjaljain**
Issue: https://github.com/cloudfoundry-incubator/service-fabrik-boshrelease/issues/30

Virtual host manager will use a seperate IaaS container to store relationship
between virtual_host instances and deployment name.

This PR complements the [PR](https://github.com/cloudfoundry-incubator/service-fabrik-broker/pull/111) raised on service-fabrik-broker.

### CODE REVIEW

**Comment by kamath-prasad** [comment]
@pranjaljain : Can you please resolve conflicts in the PR and make changes in accordance with the latest changes done to support BOSH v2.0 manifest for service-fabrik ?

**Comment by kamath-prasad** [comment]
@pranjaljain : Can you please resolve conflicts in the PR and make changes in accordance with the latest changes done to support BOSH v2.0 manifest for service-fabrik ?

**Comment by pranjaljain** [comment]
@kamath-prasad I have resolved conflicts in the PR and also done changes to support BOSH v2.0 manifest for service-fabrik.

**Comment by jagadish-kb** [comment]
Do not merge this alone. Must be merged along with broker and product component changes together.

**Pull request merged**
