### PR TITLE
Run iptables as non root

### PR DESCRIPTION
**Pull request by jagadish-kb**
Setting of iptables rules was being done as root. Per review comments/recommendation, now making use of linux capabilities to set the required capablities on iptables command and running the commands as non-user. 
To start with a user is created (if not exists) & then the commands are run as the newly created user.
Capabilities are reset post running the script.

### CODE REVIEW

**Comment by shashankmjain** [comment]
setcap CAP_NET_RAW,CAP_NET_ADMIN=ei  /sbin/xtables-multi  should work without any other user having capabilities to run the iptables.. Using eip in the above is what we should avoid.

**Comment by shashankmjain** [comment]
Also using capsh like below should work (here we use eip)
capsh --keep=1 --user=test --caps="cap_net_admin,cap_net_raw+eip" -- -c "/home/jain_sm/helloip.sh"

**Comment by jagadish-kb** [comment]
@shashankmjain since the capabilites are set and reset immediately post setting the iptable rules, the permissions on the command are reset once the script is run. So yes, no other user can modify the iptables rules.

**Comment by voelzmo** [comment]
Recommendation: don't merge this. See internal issue NGPBUG-56011 for context.

**Comment by kamath-prasad** [comment]
Closing this PR as there is a limitation with BOSH stem cell 3568.x and will be handled later with bpm.

**Pull request closed without merging**
