### PR TITLE
Fix monit script

### PR DESCRIPTION
**Pull request by RandolfWerner**
monit script needs start the process (in background) and return 0 instead of hanging as long as the process runs.

### CODE REVIEW

**Comment by kamath-prasad** [comment]
@RandolfWerner  : 

Can you please describe in the PR : 

- why this change is required ?
- Is there any issue you currently observed with the monit process start ?

**Comment by RandolfWerner** [comment]
As mentioned, if a monit script hangs it "start" action "forever" bosh will treat this as an error (please checkout monit / bosh documentation). This will leave the broker in "failing" state, e.g.:

Deployment 'service-fabrik'

Instance                                     Process State  AZ  IPs           VM CID               VM Type
broker/a05b2ef7-38bc-4a9b-a0a4-0f7897bf2427  failing        z1  10.11.252.10  i-09baf9df494d2fb64  vm_2cpu_8gb
docker/40c130d2-408a-4f7c-bce9-119394a7b728  running        z1  10.11.241.2   i-00df2d70f39e5ad86  vm_2cpu_8gb
docker/c3931810-b60f-4abf-8424-26dd9e985404  running        z1  10.11.241.0   i-0a9ffbae4f1fc19eb  vm_2cpu_8gb
docker/f49bb1f7-45eb-4a62-aea1-93e4a256fc13  running        z1  10.11.241.1   i-0cf26884e744d5803  vm_2cpu_8gb

**Comment by kamath-prasad** [comment]
@RandolfWerner : We have never observed this in any of the IAAS's or landscapes before. thanks for pointing this out !

Do you encounter such hanging often ? If yes, in which cases ? It will be helpful for us too.

**Comment by RandolfWerner** [comment]
We saw it in all our 3 service Fabrik Landscapes all the time until we fixed it locally. It doesn't matter how often one sees an error, there are a handfull lines of code which are obviously wrong. See bosh documentation: 

https://bosh.io/docs/job-lifecycle.html
https://bosh.io/docs/jobs.html#ctl 

or other bosh release ctl script implementations, e.g.:

https://github.com/cloudfoundry-incubator/haproxy-boshrelease/blob/master/jobs/haproxy/templates/haproxy_ctl

**Comment by kamath-prasad** [comment]
Closing the PR based on discussion with @marco .

**Comment by kamath-prasad** [comment]
@voelzmo : I closed the PR . Is there some confusion here ?

**Comment by voelzmo** [comment]
Oh, I see, you didn't actually merge this, but instead you're removing the `monit_debugger`. Sorry for the misunderstanding.

**Pull request closed without merging**
